#!/bin/bash
#
# Copyright (C) - 2014 Geneviève Bastien <gbastien@versatic.net>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
TEST_DESC="UST tracer - Test tracepoints using ctf global type declarations"


# Check for a running sessiond
`pidof lt-lttng-sessiond`
STOP_SESSIOND=$?

CURDIR=$(dirname $0)
TESTDIR=${CURDIR}/../../..

# Try to launch a sessiond before invoking the python test script
if [ $STOP_SESSIOND -ne 0 ]; then
	DIR=$(readlink -f ${TESTDIR})
	${DIR}/../src/bin/lttng-sessiond/lttng-sessiond --daemonize --quiet --consumerd32-path="$DIR/../src/bin/lttng-consumerd/lttng-consumerd" --consumerd64-path="$DIR/../src/bin/lttng-consumerd/lttng-consumerd"
fi

python3 ${CURDIR}/test_global_type_declarations.py

if [ $STOP_SESSIOND -ne 0 ]; then
    kill `pidof lt-lttng-sessiond`
fi
